#pragma once

#include <string>
#include <unordered_set>

namespace punp {
    namespace default_excludes {
        const std::unordered_set<std::string> default_fullname_excludes = {
            ".DS_Store",
            ".cache",
            ".cmake",
            ".eggs",
            ".git",
            ".hg",
            ".idea",
            ".svn",
            ".tox",
            ".venv",
            ".vscode",

            "__pycache__",

            "CMakeFiles",
            "Output",
            "Outputs",
            "Temp",
            "Thumbs.db",
            "Tmp",

            "bin",
            "build",
            "data",
            "dist",
            "env",
            "fig",
            "figure",
            "figures",
            "image",
            "images",
            "img",
            "imgs",
            "log",
            "logs",
            "node_modules",
            "obj",
            "out",
            "output",
            "outputs",
            "target",
            "temp",
            "tmp",
            "venv",
        };

        const std::unordered_set<std::string> default_extension_excludes = {
            ".a",
            ".aux",
            ".bin",
            ".class",
            ".csv",
            ".db",
            ".dll",
            ".doc",
            ".docx",
            ".exe",
            ".gif",
            ".gz",
            ".ico",
            ".jpg",
            ".jpeg",
            ".lock",
            ".log",
            ".o",
            ".obj",
            ".out",
            ".pdf",
            ".ppt",
            ".pptx",
            ".pyc",
            ".pyo",
            ".png",
            ".so",
            ".sql",
            ".sqlite",
            ".sqlite3",
            ".svg",
            ".tar",
            ".tif",
            ".tiff",
            ".webp",
            ".xls",
            ".xlsx",
            ".xz",
            ".zip",
        };
    } // namespace default_excludes
} // namespace punp
